# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JQ_bundle_project' do
  use_frameworks!
  pod "JQ_bundle_static", :path=>"./specs/JQ_bundle_static"
  pod "JQ_bundle_source", :path=>"./specs/JQ_bundle_source"
end
